create table `Digital Voice Recorders` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Digital Voice Recorders`  values ( 'ICD-B5', 'Sony', '11.1 x 4.4 x 0.8 inches', 'ICD-B5', '4.8 ounces', '$49.99');
create table `Computer Headsets` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Computer Headsets`  values ( '154758', 'Koss', '7.4 x 6.5 x 2.4 inches', 'black', '6.4 ounces', '7.4 x 6.5 x 2.4 inches', '$10.48');
create table `Graphics Tablets` (`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Graphics Tablets`  values ( '2.5 pounds', '11 x 2 x 1 inches', 'NULL', 'Cool-Icam');
create table `Disc Jewel Cases` (`Item model number` VARCHAR(50),`Hardware Platform` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Material Type` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `Disc Jewel Cases`  values ( '95072', 'PC', NULL, 'Verbatim', NULL, '5.8 x 5 x 0.5 inches', NULL, NULL, '3.2 ounces', '5.75 x 5 x 0.5 inches', 'NULL', NULL);
insert into `Disc Jewel Cases`  values ( '190562', NULL, '1', 'Maxell', 'Gold Black', '0.6 x 5 x 7 inches', 'Plastic', '190562', '3.2 ounces', NULL, '$8.71', '1-Pack');
create table `Television & Video` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Television & Video`  values ( 'CR130SL8', 'Sylvania', '15.7 x 13.4 x 14.6 inches', '23 pounds', 'Silver', 'NULL');
create table `Fiber Optic Cables` (`Item model number` VARCHAR(50),`Hardware Platform` VARCHAR(50),`Operating System` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Fiber Optic Cables`  values ( 'N316-25M', 'Pc', 'Windows', 'Tripp Lite', '10.4 x 7.5 x 1 inches', 'Orange', '4.8 ounces', '10.43 x 7.48 x 0.98 inches', '$38.21');
create table `Cases` (`Item model number` VARCHAR(50),`Item Display dimensions L x W x H` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `Cases`  values ( NULL, NULL, '1', 'iSkin', '9 x 4.7 x 2 inches', '0.8 ounces', NULL, 'NULL');
insert into `Cases`  values ( NULL, NULL, NULL, 'Core Cases', NULL, NULL, NULL, 'NULL');
insert into `Cases`  values ( NULL, NULL, NULL, 'Rivet', NULL, '4 ounces', NULL, 'NULL');
insert into `Cases`  values ( NULL, NULL, '1', 'Techcessory', '0.5 x 2.5 x 4 inches', '3 pounds', NULL, 'NULL');
insert into `Cases`  values ( 'APL6090', NULL, '1', 'Invisible Shield', NULL, NULL, NULL, 'NULL');
insert into `Cases`  values ( 'Prodigy FX', NULL, '1', 'B-52', '24 x 18 x 5 inches', '40 pounds', NULL, 'NULL');
insert into `Cases`  values ( 'MA497ZT/A', '90.7 x 38.7', '1', 'Apple', '3.9 x 2.2 x 1.7 inches', '5.6 ounces', 'Yes', 'NULL');
insert into `Cases`  values ( '602956002840', NULL, '1', 'Marware', '6.9 x 5.3 x 1.1 inches', '3.5 ounces', NULL, 'NULL');
insert into `Cases`  values ( NULL, NULL, '1', 'iSkin', '8 x 4.7 x 2.1 inches', '2.4 ounces', NULL, 'NULL');
insert into `Cases`  values ( NULL, NULL, NULL, 'MyGift', NULL, NULL, NULL, 'NULL');
insert into `Cases`  values ( '602956003595', NULL, '1', 'Marware', '6.1 x 3.4 x 0.7 inches', '1.4 ounces', NULL, 'NULL');
create table `DVD Players` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Weight` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Built In Decoders` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`Special Features` VARCHAR(50),`price` VARCHAR(50));
insert into `DVD Players`  values ( 'Imported (Malaysia)', 'DVP-NS700P', NULL, 'Sony', '18 x 14 x 4 inches', NULL, '7.3 pounds', '2 AA batteries required. (included)', NULL, NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'DV2140', NULL, 'Go Video', '20.2 x 14.3 x 6.4 inches', NULL, '10.8 pounds', NULL, NULL, NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'DVD712AT', NULL, 'Philips', '19.2 x 14.6 x 5.6 inches', NULL, '10.8 pounds', '2 AA batteries required. (included)', 'Yes', NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'SD4900', NULL, 'Toshiba', '19.2 x 13 x 5.3 inches', NULL, '10 pounds', NULL, 'Yes', NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'SD-6000', NULL, 'Toshiba', '7.8 x 16.9 x 1.6 inches', NULL, '4.5 pounds', NULL, NULL, 'Black', NULL, 'NULL');
insert into `DVD Players`  values ( NULL, NULL, '4.6 Pounds', NULL, NULL, NULL, '4 pounds', NULL, NULL, NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'XVN332S', NULL, 'JVC', '7.6 x 16.9 x 1.5 inches', 'No', '3.3 pounds', NULL, NULL, 'Silver', NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'DVP642', NULL, 'Philips', '17.1 x 9.8 x 1.7 inches', 'PAL to NTSC NTSC to PAL, Region Conversion, Divx', '7 pounds', NULL, NULL, 'Silver', NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'XV-FA95GD', NULL, 'JVC', '17.2 x 17.7 x 4.1 inches', NULL, '12.4 pounds', NULL, 'Yes', 'Gold', NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'TFDVD-7700', NULL, 'Coby', '10.2 x 9.4 x 6.3 inches', NULL, '5 pounds', NULL, 'Yes', NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'SD-P2600', NULL, 'Toshiba', '7 x 1.2 x 10.2 inches', NULL, '4 pounds', NULL, 'Yes', NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'DVD-LV55', NULL, 'Panasonic', '12.2 x 7 x 2 inches', NULL, '1.2 pounds', NULL, 'Yes', 'silver', 'Analog Audio x 1, Composite x 1', 'NULL');
insert into `DVD Players`  values ( NULL, 'SDP1000', NULL, 'Toshiba', '10.7 x 9 x 3.1 inches', NULL, '2.7 pounds', NULL, 'Yes', NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'XVN420B', NULL, 'JVC', '20.5 x 10.1 x 3.8 inches', NULL, '14 pounds', NULL, NULL, NULL, NULL, 'NULL');
insert into `DVD Players`  values ( NULL, 'SD-2900', NULL, 'Toshiba', '19.2 x 13.1 x 5.2 inches', NULL, '7.5 pounds', NULL, 'Yes', 'Black', NULL, 'NULL');
create table `Car Video` (`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Brand` VARCHAR(50),`price` VARCHAR(50));
insert into `Car Video`  values ( 'MP7610', '13.5 x 12 x 3 inches', 'MP7610', '5.7 pounds', 'Jensen', 'NULL');
create table `Computer Speakers` (`price` VARCHAR(50),`Brand Name` VARCHAR(50),`Power Source` VARCHAR(50));
insert into `Computer Speakers`  values ( 'NULL', 'DigitalAge', 'Corded-Electric');
create table `Dual-channel Amplifiers` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Warranty` VARCHAR(50),`price` VARCHAR(50));
insert into `Dual-channel Amplifiers`  values ( 'Imported (China)', 'RSD250.2', NULL, '17 x 14 x 5.2 inches', '11.3 pounds', '1 Year', 'NULL');
insert into `Dual-channel Amplifiers`  values ( NULL, 'RBLA220', '4.3 Pounds', NULL, '5 pounds', NULL, 'NULL');
create table `Trackballs` (`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Trackballs`  values ( '9.6 ounces', '8.4 x 6.7 x 4.1 inches', 'Silver', 'NULL', 'Microsoft');
create table `Plasma TVs` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Display Height` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Plasma TVs`  values ( '50PF7320A/37', 'Philips', '58.5 x 39 x 15 inches', NULL, '137 pounds', NULL, NULL, 'NULL');
insert into `Plasma TVs`  values ( 'SPR4212', 'Samsung', '41.6 x 28.5 x 3.9 inches', NULL, '88.4 pounds', NULL, NULL, 'NULL');
insert into `Plasma TVs`  values ( NULL, 'Akai', NULL, NULL, NULL, NULL, NULL, 'NULL');
insert into `Plasma TVs`  values ( 'TH-42PD50UB', 'Panasonic', '49.7 x 37.3 x 20.4 inches', NULL, '105.8 pounds', NULL, NULL, 'NULL');
insert into `Plasma TVs`  values ( 'FPT6374', 'Samsung', '3.4 x 60.2 x 39.4 inches', '42.9 inches', '191.7 pounds', '2 AAA batteries required. (included)', 'Black', 'NULL');
insert into `Plasma TVs`  values ( 'TH-42PD50UA', 'Panasonic', '49.7 x 37.3 x 20.4 inches', NULL, '105.8 pounds', NULL, NULL, 'NULL');
create table `Photo Paper` (`Item model number` VARCHAR(50),`Form Size` VARCHAR(50),`Sheet Size` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Material Type` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Paper Weight` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `Photo Paper`  values ( 'Q5492A', '13" by 19"', 'see description', '1', 'HP', 'White', '19.5 x 13.5 x 1 inches', 'Matte Photo Paper for Inkjet Printer', 'Q5492A', '4.2 pounds', '57', 'NULL', '13" x 19"');
create table `VGA Cables` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Batteries Required?` VARCHAR(50),`Brand Name` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Color` VARCHAR(50),`Origin` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Certification` VARCHAR(50),`Warranty Description` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`Batteries Included?` VARCHAR(50),`Usage` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `VGA Cables`  values ( '253-506IV', NULL, NULL, 'Steren', NULL, NULL, NULL, '6 x 2 x 6 inches', NULL, NULL, '12.8 ounces', '6 x 2 x 6 inches', NULL, NULL, '$12.00', NULL);
insert into `VGA Cables`  values ( 'MXT101MMLP15', 'MXT101MMLP15', 'No', NULL, '1', 'Black', 'China', '5.5 x 0.6 x 11.2 inches', 'No', 'Lifetime warranty', '8.2 ounces', NULL, 'No', 'personal', '$14.24', 'Without CE');
create table `Cat 6 Cables` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Cat 6 Cables`  values ( 'R6D026-AB6-IVO', 'Belkin', '4.4 x 2.8 x 0.8 inches', 'Ivory', '1 ounces', NULL, '$6.00');
insert into `Cat 6 Cables`  values ( '27180', 'C2G', '6 x 4 x 0.3 inches', 'Red', '0.8 ounces', '6 x 4 x 0.3 inches', '$5.20');
insert into `Cat 6 Cables`  values ( '27166', 'C2G/ Cables To Go', '7 x 7 x 2 inches', 'White', '1.1 pounds', '7 x 7 x 2 inches', '$19.68');
create table `Audio Docks` (`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Power Source Type` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Audio Docks`  values ( '1', 'SDI Technologies', '9.3 x 8.5 x 3.6 inches', 'Battery/Corded Electric', '2.5 pounds', 'NULL');
create table `Security Sensors` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Warranty Description` VARCHAR(50),`Finish` VARCHAR(50),`Power Source` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `Security Sensors`  values ( 'RH-6030-WH5-A', 'SL-6030-WH', '2 years', 'White', 'Battery Powered', '1', 'White', '7.1 x 5.9 x 4.1 inches', '8.8 ounces', 'Yes', 'NULL');
create table `RCA Cables` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `RCA Cables`  values ( 'T09082', 'RCA', '14.9 x 12.5 x 13 inches', '24.5 pounds', 'Yes', 'NULL');
create table `Disc Storage Wallets` (`Brand` VARCHAR(50),`price` VARCHAR(50));
insert into `Disc Storage Wallets`  values ( 'Plasticolor', 'NULL');
create table `Serial Cables` (`price` VARCHAR(50),`Screen Size` VARCHAR(50));
insert into `Serial Cables`  values ( '$4.00', '120 inches');
create table `Amplifiers` (`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50));
insert into `Amplifiers`  values ( '17 pounds', '24.2 x 13.2 x 5 inches', 'NULL');
create table `Portable & Novelty TVs` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `Portable & Novelty TVs`  values ( 'VV1301', 'Quasar', '18.4 x 18.3 x 17.7 inches', '29.4 pounds', '2 AA batteries required. (included)', 'Yes', 'NULL');
create table `Folio Cases` (`Item model number` VARCHAR(50),`Hardware Platform` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Folio Cases`  values ( '198111291', 'PC', 'Samsonite', '16.6 x 15.4 x 4.7 inches', 'Black', '1 ounces', '$49.49');
create table `Minis` (`Processor` VARCHAR(50),`Screen Resolution` VARCHAR(50),`Number of USB 2.0 Ports` VARCHAR(50),`price` VARCHAR(50),`RAM` VARCHAR(50),`Max Screen Resolution` VARCHAR(50),`Graphics Coprocessor` VARCHAR(50),`Memory Speed` VARCHAR(50),`Hard Drive` VARCHAR(50),`Card Description` VARCHAR(50),`Chipset Brand` VARCHAR(50),`Wireless Type` VARCHAR(50));
insert into `Minis`  values ( '1.66 GHz Intel Core Duo', '1920 x 1200', '4', 'NULL', '512 MB DDR2', '1920 x 1200 pixels', 'Intel GMA 950', '667 MHz', '80 GB SATA', 'Graphics Media Accelerator950', 'Intel', '802.11G');
create table `Power Converters` (`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Brand` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`California residents` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50),`Voltage` VARCHAR(50));
insert into `Power Converters`  values ( '852-2000', '14 x 12 x 9 inches', 'Xantrex', '8522000', '27.6 pounds', 'Click here for Proposition 65 warning', 'Yes', 'NULL', '115 volts');
create table `Slide, Negative & Print Pages` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Slide, Negative & Print Pages`  values ( '060-0610', 'Print File', 'Clear', '11 x 8.5 x 0 inches', '0600610', '0.2 ounces', '$15.98');
create table `Speaker Wire` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Weight` VARCHAR(50));
insert into `Speaker Wire`  values ( '1.4 pounds', 'S14-50 MTA', '4.8 x 4.8 x 2.2 inches', 'NULL', '1.3 Pounds');
create table `Towers` (`Screen Resolution` VARCHAR(50),`Number of USB 2.0 Ports` VARCHAR(50),`Screen Size` VARCHAR(50),`price` VARCHAR(50),`RAM` VARCHAR(50),`Max Screen Resolution` VARCHAR(50),`Wireless Type` VARCHAR(50),`Graphics Card Ram Size` VARCHAR(50),`Card Description` VARCHAR(50),`Hard Drive` VARCHAR(50),`Graphics Coprocessor` VARCHAR(50),`Chipset Brand` VARCHAR(50),`Processor` VARCHAR(50));
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '512 MB', NULL, NULL, NULL, NULL, '200 GB', NULL, NULL, '3 GHz Intel Pentium 4');
insert into `Towers`  values ( '1680 x 1050 pixels', '3', '20 inches', 'NULL', '256 MB DDR', NULL, '802.11g 108 Mbps', '64 MB', 'NVIDIA GeForce FX 5200 Ultra', '160 GB', 'NVIDIA GeForce FX 5200 Ultra', 'NVIDIA', '1.8 GHz PowerPC G5');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '1000 MB ddr_sdram', NULL, NULL, NULL, NULL, '200 GB', NULL, NULL, '3.2 GHz Intel Pentium 4');
insert into `Towers`  values ( NULL, '7', NULL, 'NULL', '512 MB ddr2_sdram', NULL, NULL, '128 MB', 'Integrated Intel GMA 900', '200 GB', NULL, NULL, '2.93 GHz Intel Pentium 4');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '128 MB', NULL, NULL, NULL, 'Intel Extreme Graphics 3D', '40 MB', NULL, NULL, '2 GHz Intel Celeron');
insert into `Towers`  values ( '1440_x_900', NULL, '17 inches', 'NULL', '1024 MB', NULL, NULL, NULL, NULL, '120 GB', 'geforce', NULL, '1730 MHz Intel Core Duo');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '256 MB', NULL, NULL, NULL, NULL, '60 GB', NULL, NULL, '2.66 GHz Intel Celeron');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '256.0 ddr_sdram', NULL, NULL, NULL, 'S3 graphics UniChrome 3D graphics', '80 GB', NULL, NULL, '3.06 Intel Celeron');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '256 MB ddr_sdram', NULL, NULL, NULL, NULL, '80 GB', NULL, NULL, '2.8 GHz Intel Celeron');
insert into `Towers`  values ( '1024-by-768', '5', '15 inches', 'NULL', '256 MB SDRAM', '1024 x 768 pixels', NULL, '32 MB', 'nVIDIA GeForce2 MX', '60 GB ATA', 'NVIDIA GeForce2 MX', 'NVIDIA', '800 MHz PowerPC G4');
insert into `Towers`  values ( NULL, NULL, NULL, 'NULL', '192 MB', NULL, NULL, NULL, NULL, '6.4 GB', NULL, NULL, '450 MHz Intel Pentium III');
create table `Monitor Arms & Stands` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Display Height` VARCHAR(50),`Item Weight` VARCHAR(50),`California residents` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Monitor Arms & Stands`  values ( '45-179-195', 'Ergotron', '18.5 x 10.5 x 6 inches', '102.4 inches', '12.7 pounds', 'Click here for Proposition 65 warning', 'Black', 'NULL');
create table `Armbands` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Armbands`  values ( 'F8M052-BLK', '1', 'Belkin', '7.5 x 5.5 x 3.5 inches', '5 ounces', 'NULL');
create table `Lamps` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Batteries Required?` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50),`Material` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Style` VARCHAR(50),`Item Weight` VARCHAR(50),`Finish` VARCHAR(50),`Batteries Included?` VARCHAR(50),`Specific Uses` VARCHAR(50),`Wattage` VARCHAR(50),`Shade Material` VARCHAR(50),`Brand` VARCHAR(50),`Voltage` VARCHAR(50));
insert into `Lamps`  values ( 'KSB-1250', NULL, NULL, NULL, 'Smith-Victor', '$635.00', NULL, '408087', NULL, '39.5 pounds', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
insert into `Lamps`  values ( NULL, 'DEK', 'No', '4.5 x 2.2 x 1.7 inches', NULL, '$33.00', NULL, NULL, NULL, '1.6 ounces', NULL, 'No', 'personal', '500.00', NULL, 'GE', '120 volts');
insert into `Lamps`  values ( NULL, NULL, NULL, NULL, NULL, 'NULL', 'Metal', NULL, NULL, NULL, NULL, NULL, 'personal', NULL, NULL, 'WGC', NULL);
insert into `Lamps`  values ( NULL, 'VF_VT062-035', NULL, NULL, NULL, 'NULL', 'Steel', NULL, 'Modern', NULL, 'Iron', NULL, 'personal', NULL, 'Linen', 'Century Nice', NULL);
insert into `Lamps`  values ( NULL, NULL, NULL, '3.2 x 3.2 x 3.1 inches', '3M', 'NULL', NULL, '59995', NULL, '1.6 ounces', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
create table `Computers & Accessories` (`Item model number` VARCHAR(50),`Graphics Card Ram Size` VARCHAR(50),`Screen Resolution` VARCHAR(50),`Number of USB 2.0 Ports` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`RAM` VARCHAR(50),`Processor` VARCHAR(50),`Item Weight` VARCHAR(50),`Card Description` VARCHAR(50),`Hard Drive` VARCHAR(50),`price` VARCHAR(50),`National Stock Number` VARCHAR(50));
insert into `Computers & Accessories`  values ( '765815U', NULL, NULL, NULL, 'Lenovo', '12.6 x 9.7 x 4.7 inches', NULL, NULL, '5.8 pounds', NULL, NULL, 'NULL', NULL);
insert into `Computers & Accessories`  values ( NULL, NULL, NULL, NULL, 'Logitech', NULL, NULL, NULL, NULL, NULL, NULL, 'NULL', NULL);
insert into `Computers & Accessories`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2 MB', '$26.99', '5975-01-575-1654');
insert into `Computers & Accessories`  values ( NULL, '64 MB', '1280-by-800', '4', NULL, NULL, '512 MB', '2.66 GHz Mobile Intel Pentium 4 Processor', NULL, 'Nvidia GeForce4 440 Go', '40 GB', 'NULL', NULL);
create table `Component Subwoofers` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Weight` VARCHAR(50),`Origin` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `Component Subwoofers`  values ( 'PLQB10', NULL, '22 Pounds', NULL, '17 x 12 x 12 inches', '21 pounds', NULL, '$51.86');
insert into `Component Subwoofers`  values ( 'TSSW2541D', 'Mobile Audio: 1 Year Parts and Labor', NULL, NULL, '4.8 x 12 x 12 inches', '10.5 pounds', 'Yes', 'NULL');
insert into `Component Subwoofers`  values ( '07CVR84', NULL, NULL, NULL, '10.4 x 10.3 x 6.3 inches', '7 pounds', NULL, 'NULL');
insert into `Component Subwoofers`  values ( 'TSSW3041D', 'Mobile Audio: 1 Year Parts and Labor', NULL, NULL, '15 x 15 x 6 inches', '16.4 pounds', NULL, 'NULL');
insert into `Component Subwoofers`  values ( 'XS-L1090P5', NULL, NULL, 'Made in USA and Imported', NULL, '3 pounds', NULL, 'NULL');
create table `Sleeves` (`Item model number` VARCHAR(50),`Closure` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Total Recycled Content Percentage` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Material Type` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Post-Consumer Recycled Content Percentage` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `Sleeves`  values ( 'D978-4', 'Hook and Loop', '1', 'SOLO', '0.1', 'Black', '18 x 13.5 x 8 inches', 'leather', 'D978-4', '7.3 pounds', '0.05', '$99.11', 'One Size');
create table `Sensors` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Batteries Required?` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Warranty Description` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Batteries Included?` VARCHAR(50),`price` VARCHAR(50));
insert into `Sensors`  values ( 'PS-101', 'PS-101', 'Yes', '1', '3.5 x 2 inches', '1 Year Warranty (Repair or Replace)', '2.5 pounds', '1 9V batteries required. (included)', 'Yes', '$23.50');
create table `FM Transmitters` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Brand` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50));
insert into `FM Transmitters`  values ( 'TXM-HK01', NULL, '3.2 Pounds', '10 x 4.9 x 3 inches', NULL, NULL, '1.4 pounds', NULL, NULL, '$59.99');
insert into `FM Transmitters`  values ( 'FMMOD01', '1', NULL, '7.2 x 5 x 2 inches', NULL, NULL, '8.8 ounces', NULL, 'SoundKase', '$19.95');
insert into `FM Transmitters`  values ( 'VRTP4N1', NULL, NULL, '8.6 x 7 x 2.5 inches', 'Yes', 'VRTP4N1C', '10.1 ounces', 'VR3', NULL, 'NULL');
create table `Floppy Diskettes` (`Item model number` VARCHAR(50),`Sheet Size` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Floppy Diskettes`  values ( 'Q5482A', 'Arch E or 6', '1', 'HP', '38 x 4.6 x 4.3 inches', 'Q5482A', '7.2 pounds', 'NULL');
create table `Overhead Video` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Display Type` VARCHAR(50),`Weight` VARCHAR(50),`price` VARCHAR(50),`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `Overhead Video`  values ( NULL, NULL, NULL, NULL, 'NULL', '5.7 pounds', NULL);
insert into `Overhead Video`  values ( 'PLDSV71GR', '1-YEAR', 'LCD', '3.1 Pounds', 'NULL', '2.6 pounds', '1.8 x 10.4 x 17.5 inches');
create table `Accessories & Supplies` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Accessories & Supplies`  values ( 'Amazon 260-1-N', 'Cable Wholesale', '1.2 x 1.2 x 1.2 inches', NULL, '3.2 ounces', '1.18 x 1.18 x 1.18 inches', '$4.67');
insert into `Accessories & Supplies`  values ( '320-120WH', 'CableWholesale', '1.2 x 1.2 x 1.2 inches', 'White', '0.8 ounces', '1.2 x 1.2 x 1.2 inches', '$5.11');
create table `Connectors & Adapters` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Connectors & Adapters`  values ( 'USB_A_F-USB_B_M', 'Generic', '3 x 3 x 3 inches', 'Black', '0.3 ounces', '3 x 3 x 3 inches', '$1.34');
create table `Projector Mounts` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`California residents` VARCHAR(50),`price` VARCHAR(50));
insert into `Projector Mounts`  values ( 'CGUPM06-B', 'Vantage Point', '11.5 x 3.5 x 8.5 inches', '3.3 pounds', 'Click here for Proposition 65 warning', '$53.29');
create table `Portable CD Players` (`Origin` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Portable CD Players`  values ( 'Imported (Mexico)', '1', 'Bose', '16.9 x 13 x 8.2 inches', '7 pounds', 'NULL');
create table `Batteries` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Battery Cell Type` VARCHAR(50),`Optical Drive Type` VARCHAR(50),`Brand Name` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color2` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries Included?` VARCHAR(50),`Voltage` VARCHAR(50),`Battery Type` VARCHAR(50),`Description Pile` VARCHAR(50),`price` VARCHAR(50));
insert into `Batteries`  values ( NULL, NULL, NULL, NULL, 'AT&T', NULL, NULL, '4.1 x 2.2 x 1.3 inches', NULL, '00249', '3.2 ounces', NULL, NULL, NULL, NULL, '$16.99');
insert into `Batteries`  values ( 'B-5903', NULL, NULL, 'Brand New with Manufacturer Warranty', 'Duracell', NULL, NULL, '5.5 x 3.9 x 0.8 inches', 'Grey', NULL, '1.1 pounds', NULL, '14.4 volts', 'Lithium-Ion (Li-Ion)', NULL, 'NULL');
insert into `Batteries`  values ( '1X390, 2X019, 312-0073, Dell Axim X5', '1X390, 2X019, 312-0073, Axim X5', 'Lithium Ion', NULL, NULL, '1', 'Silver', '3.1 x 2.3 x 0.2 inches', NULL, NULL, '1.6 ounces', 'No', '3.7 volts', NULL, 'battery_type_lithium_ion', '$23.90');
create table `TV Ceiling & Wall Mounts` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`California residents` VARCHAR(50),`Color Name` VARCHAR(50),`Special Features` VARCHAR(50),`price` VARCHAR(50));
insert into `TV Ceiling & Wall Mounts`  values ( '2N1-LP', 'OmniMount', '34 x 15.8 x 2.8 inches', '24 pounds', NULL, 'Silver', 'Screen Size compatibility: 37/63"', 'NULL');
insert into `TV Ceiling & Wall Mounts`  values ( 'VMF', 'Sanus', '11 x 1.5 x 9 inches', '1.6 pounds', 'Click here for Proposition 65 warning', NULL, NULL, '$19.94');
create table `Laser Printer Drums & Toner` (`Item model number` VARCHAR(50),`Item Weight` VARCHAR(50),`National Stock Number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Ink Color` VARCHAR(50),`price` VARCHAR(50));
insert into `Laser Printer Drums & Toner`  values ( 'C780H1CG', '5.3 pounds', '3610-01-585-6815', '1', 'Lexmark', 'Hy Cyan', '19.5 x 7 x 9 inches', 'C780H1CG', 'Cyan', '$35.00');
insert into `Laser Printer Drums & Toner`  values ( '400969', '12.8 ounces', NULL, '1', 'Ricoh', 'Cyan (Blue)', '10.8 x 4.2 x 2 inches', '400969', NULL, '$37.99');
insert into `Laser Printer Drums & Toner`  values ( 'C9202KH', '6.4 pounds', '7510-01-549-7792', '1', 'Lexmark', 'Black', '21.7 x 10.1 x 6.4 inches', 'C9202KH', 'Black', '$157.15');
create table `Monitors` (`Item model number` VARCHAR(50),`National Stock Number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Color Name` VARCHAR(50),`Screen Size` VARCHAR(50),`price` VARCHAR(50));
insert into `Monitors`  values ( 'LVM-37W3', NULL, 'Westinghouse', '37.3 x 8.2 x 25.9 inches', '50 pounds', '2 AAA batteries required. (included)', 'Black/Dark Silver', NULL, 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '20 inches', 'NULL');
insert into `Monitors`  values ( NULL, '7025-01-514-2526', NULL, NULL, NULL, NULL, NULL, '17 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '17 inches', 'NULL');
insert into `Monitors`  values ( NULL, '7025-01-511-4282', NULL, NULL, NULL, NULL, NULL, '21 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '16 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '19 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '15 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '17 inches', 'NULL');
insert into `Monitors`  values ( NULL, NULL, NULL, NULL, NULL, NULL, NULL, '17 inches', 'NULL');
insert into `Monitors`  values ( '342i', NULL, 'Syntax', '48 x 15 x 38 inches', '107 pounds', NULL, 'Silver', NULL, 'NULL');
insert into `Monitors`  values ( '337H', NULL, 'Syntax', '41 x 12 x 32 inches', '65 pounds', NULL, 'Silver', NULL, 'NULL');
create table `Car Audio` (`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Car Audio`  values ( '12 ounces', 'NULL');
create table `Speakers` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Warranty` VARCHAR(50));
insert into `Speakers`  values ( '10.3 pounds', '6349', '5.4 x 16.4 x 12 inches', 'NULL', '1- YEAR');
create table `Printer Labels: Laser & Inkjet` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Material Type` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `Printer Labels: Laser & Inkjet`  values ( 'DYM520109', '1', 'DYMO', 'Black', '2 x 2 x 0.5 inches', 'vinyl', 'DYM520109', '1.6 ounces', '$2.72', '1');
create table `Traditional Laptops` (`Screen Resolution` VARCHAR(50),`Number of USB 2.0 Ports` VARCHAR(50),`National Stock Number` VARCHAR(50),`Wireless Type` VARCHAR(50),`price` VARCHAR(50),`RAM` VARCHAR(50),`Max Screen Resolution` VARCHAR(50),`Graphics Coprocessor` VARCHAR(50),`Graphics Card Ram Size` VARCHAR(50),`Card Description` VARCHAR(50),`Hard Drive` VARCHAR(50),`Screen Size` VARCHAR(50),`Processor` VARCHAR(50));
insert into `Traditional Laptops`  values ( '1024-by-768', '2', NULL, NULL, 'NULL', '0.25 GB ddr_sdram', NULL, 'radeon', '32 MB', 'ATI Mobility Radeon 9200', '60 GB', '14.1 inches', '1.33 GHz PowerPC G4');
insert into `Traditional Laptops`  values ( '1024-by-768', '3', NULL, NULL, 'NULL', '512 MB ddr_sdram', NULL, NULL, '64 MB', 'ATI RADEON IGP 345M', '40 GB', NULL, '2.66 GHz Intel Pentium 4');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11 B/G, 802.11B', 'NULL', '512 MB DDR2 SDRAM', NULL, 'Integrated', NULL, NULL, '80 GB', '15.4 inches', '1.8 GHz AMD Sempron');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11abg, 802.11A', 'NULL', '2 GB DDR2 SDRAM', NULL, 'Radeon', NULL, NULL, '160 GB', '15.4 inches', '2 GHz Intel Core 2 Duo');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, NULL, 'NULL', '512 MB', NULL, NULL, NULL, NULL, '100 GB', '15.4 inches', 'Pentium');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11 B/G, 802.11B', 'NULL', '1000 MB', NULL, 'Intel Integrated Graphics', NULL, NULL, '100 GB', '15.4 inches', '2 GHz Intel Pentium M');
insert into `Traditional Laptops`  values ( '1280-by-854', NULL, '7010-01-513-5659', '802.11B', 'NULL', '512 MB SDRAM', '1280 x 854', 'radeon', '64 MB', 'ATI Mobility Radeon 9000', '60 GB 60GB', '15.2 inches', '1 GHz PowerPC G4');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11abg, 802.11A', 'NULL', '2000 MB', '1440 x 900', 'NVIDIA GeForce', NULL, NULL, '160 GB', '17 inches', '1.6 GHz Intel Core Duo');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11abg, 802.11 a/b/g/n, 802.11A', 'NULL', '2000 MB', NULL, 'NVIDIA GeForce', NULL, NULL, '320 GB', '17 inches', '2 GHz Intel Core Duo');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11 B/G, 802.11B', 'NULL', '1 GB DDR2 SDRAM', NULL, 'NVIDIA GeForce', NULL, NULL, '100 GB', '15.4 inches', '1.6 GHz AMD Turion 64 X2');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11abg, 802.11n, 802.11A', 'NULL', '2 GB', NULL, NULL, NULL, NULL, '250 GB', '17 inches', '1.66 GHz Intel Core 2 Duo');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11 B/G, 802.11B', 'NULL', '1 GB DDR2 SDRAM', NULL, 'Integrated', NULL, NULL, '120 GB', '15 inches', '1.6 GHz AMD Turion 64 X2');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11 B/G, 802.11B', 'NULL', '512 MB ddr2', NULL, 'Intel Integrated Graphics', NULL, NULL, '80 GB', '15.4 inches', '1.5 GHz Intel Celeron');
insert into `Traditional Laptops`  values ( NULL, NULL, NULL, '802.11abg, 802.11 a/g/n, 802.11A, 802.11 A/G', 'NULL', '2000 MB', NULL, 'Intel Integrated Graphics', NULL, NULL, '160 GB', '15.4 inches', '1.73 GHz Intel Core Duo');
create table `Car CD Visors` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Brand` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Cover Included` VARCHAR(50),`price` VARCHAR(50));
insert into `Car CD Visors`  values ( 'China', 'AV-12', '12.2 x 5.9 x 0.2 inches', 'Case Logic', 'AV-12', '3.2 ounces', 'one CD car visor organizer', '$7.99');
create table `Internal TV Tuner & Capture Cards` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Internal TV Tuner & Capture Cards`  values ( '7 pounds', 'HFA100', '14.8 x 12.5 x 4.8 inches', 'NULL', 'Humax');
create table `Mouse Pads` (`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Material Type` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Mouse Pads`  values ( 'Datexx', '13.3 x 9.8 x 1.7 inches', 'Leather', '215WTLG', '0.3 ounces', 'NULL');
create table `Televisions` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Televisions`  values ( 'Made in USA or Imported', 'KV27FS120', 'Sony', '19.7 x 30.3 x 23.3 inches', '60 pounds', NULL, NULL, 'silver', 'NULL');
insert into `Televisions`  values ( NULL, 'C30W46', 'Zenith', '21.7 x 23.7 x 35.9 inches', '149 pounds', NULL, NULL, NULL, 'NULL');
insert into `Televisions`  values ( NULL, '50HM66', 'Toshiba', '47.2 x 16.6 x 30.7 inches', '83.2 pounds', NULL, NULL, NULL, 'NULL');
insert into `Televisions`  values ( NULL, '61SDX01B', 'HGST, a Western Digital Company', NULL, '1 pounds', NULL, NULL, NULL, 'NULL');
insert into `Televisions`  values ( NULL, '32RS400', 'Sharp', NULL, '113 pounds', NULL, NULL, NULL, 'NULL');
insert into `Televisions`  values ( NULL, '30DF56', 'Toshiba', '22.2 x 31.4 x 21.6 inches', '128 pounds', NULL, NULL, NULL, 'NULL');
insert into `Televisions`  values ( NULL, 'PT47WX53', 'Panasonic', '48.7 x 43.7 x 24.6 inches', '150 pounds', NULL, 'Yes', NULL, 'NULL');
insert into `Televisions`  values ( NULL, '30DV693R', 'Philips', '35 x 23.5 x 21.5 inches', '121.1 pounds', NULL, 'Yes', NULL, 'NULL');
insert into `Televisions`  values ( NULL, 'PT-50LCZ70', 'Panasonic', '52.6 x 37.3 x 20.7 inches', '79 pounds', '2 AAA batteries required. (included)', NULL, NULL, 'NULL');
create table `Conduit` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Conduit`  values ( '75-100BL', '75-100BL', '100', '12 x 12 x 11.3 inches', '430 pounds', '$56.34');
create table `Inkjet Printer Ink` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`price` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Inkjet Printer Ink`  values ( '10 pounds', 'PGCL 12PK', 'NULL', 'PGCL 12PK', 'IEM');
create table `Portable DVD Players` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Portable DVD Players`  values ( 'PD-100', 'Apex', '1.8 x 6.5 x 6.5 inches', '1 pounds', 'Yes', NULL, 'NULL');
insert into `Portable DVD Players`  values ( 'XDVD270', 'Dual Electronics', '12.8 x 9.2 x 9.1 inches', '5.8 pounds', NULL, 'Black', 'NULL');
insert into `Portable DVD Players`  values ( 'I1055-BLK', 'iLuv', '9 x 11.5 x 8 inches', '6.3 pounds', NULL, NULL, 'NULL');
create table `TV Turntables` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `TV Turntables`  values ( 'TV20', 'Sanus', '20 x 25 x 1.5 inches', '9 pounds', 'Black', 'NULL');
create table `Bags, Cases & Sleeves` (`price` VARCHAR(50),`Screen Size` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Bags, Cases & Sleeves`  values ( '$65.48', '15.6 inches', NULL);
insert into `Bags, Cases & Sleeves`  values ( 'NULL', NULL, 'Shoreline');
create table `Chargers & Adapters` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `Chargers & Adapters`  values ( '30X3-03220', 'CableWholesale', '1.2 x 1 x 1 inches', 'Silver', '0.3 ounces', '1.2 x 1 x 1 inches', '$4.30');
insert into `Chargers & Adapters`  values ( '10W1-15306', 'CableWholesale', '72 x 2 x 3 inches', 'Black', '2.4 ounces', '72 x 2 x 3 inches', '$7.79');
create table `LED & LCD TVs` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Display Height` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `LED & LCD TVs`  values ( 'LNS-2351W', 'Samsung', '9 x 29 x 26 inches', NULL, '27 pounds', NULL, NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'kp-53hs30', 'Sony', '24.9 x 46.5 x 55.9 inches', NULL, '85 pounds', NULL, NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( '6620LF4', 'Sylvania', '11 x 19 x 25 inches', NULL, '19 pounds', '2 AA batteries required. (included)', NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'LC20SH7U', 'Sharp', '8.9 x 21.3 x 17.2 inches', '15.7 inches', '13.3 pounds', NULL, NULL, 'Black', 'NULL');
insert into `LED & LCD TVs`  values ( 'Z32LC2D', 'LG', '35.9 x 27.4 x 12.4 inches', NULL, '56.7 pounds', NULL, NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'EV-1503', 'SVA', '13.8 x 7.1 x 15.7 inches', NULL, '9.5 pounds', NULL, 'Yes', NULL, 'NULL');
insert into `LED & LCD TVs`  values ( NULL, 'VIZIO', '33.1 x 5 x 25.2 inches', NULL, '34.4 pounds', NULL, NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'HLP5085W', 'Samsung', '54.7 x 53.6 x 20.5 inches', NULL, '125.4 pounds', NULL, 'Yes', 'black, silver', 'NULL');
insert into `LED & LCD TVs`  values ( 'LN-R238WA', 'Samsung', '23 x 19.1 x 8.1 inches', NULL, '25 pounds', NULL, NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'LNT4053H', 'Samsung', '4.2 x 39 x 25.8 inches', NULL, '39.5 pounds', '2 AAA batteries required. (included)', NULL, 'Black', 'NULL');
insert into `LED & LCD TVs`  values ( 'LC-45GD6U', 'Sharp', '47.6 x 16 x 35.5 inches', NULL, '100 pounds', NULL, 'Yes', NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'LC-37D4U', 'Sharp', '43.5 x 25.5 x 12 inches', NULL, '65 pounds', '2 AAA batteries required. (included)', NULL, NULL, 'NULL');
insert into `LED & LCD TVs`  values ( 'H200', 'BenQ', '27.2 x 25.5 x 11.2 inches', NULL, '35 pounds', NULL, NULL, NULL, 'NULL');
create table `Projection Screens` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Projection Screens`  values ( '90614', '1', 'Da-Lite', '84 x 9 x 6 inches', '90614', '23.8 pounds', '$156.20');
create table `TV Remote Controls` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Batteries Required?` VARCHAR(50),`Number Of Holes` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Origin` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `TV Remote Controls`  values ( 'KR22A', 'KR22A', 'No', '1', '1', 'China', '6 x 5 x 5 inches', '0.8 ounces', '$16.99');
create table `Mice` (`Item model number` VARCHAR(50),`Hardware Platform` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `Mice`  values ( 'OPTIGO', 'PC', 'Macally', 'NULL', NULL, '5.6 ounces', NULL, NULL);
insert into `Mice`  values ( 'F8E841-BLK', NULL, 'Belkin', '$5.99', 'black', '8.5 ounces', '1.75 x 5 x 9 inches', '1.8 x 5 x 9 inches');
create table `Speaker Mounts` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `Speaker Mounts`  values ( 'PM732W', 'Peerless', '10 x 9.2 x 2.5 inches', '2.2 pounds', 'White', 'NULL');
insert into `Speaker Mounts`  values ( '60.0WB-B', 'OmniMount', '13 x 11.5 x 4.5 inches', '4 pounds', NULL, 'NULL');
create table `Power Cables` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Usage` VARCHAR(50),`price` VARCHAR(50));
insert into `Power Cables`  values ( '148-0025', '148 0025', '1', '7.5 x 4 x 0.1 inches', '0.3 ounces', 'personal', '$0.99');
create table `Cat 5e Cables` (`Item model number` VARCHAR(50),`Part Number` VARCHAR(50),`Operating System` VARCHAR(50),`Brand Name` VARCHAR(50),`Item Package Quantity` VARCHAR(50),`Color` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color2` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`Usage` VARCHAR(50),`Hardware Platform` VARCHAR(50),`price` VARCHAR(50),`Size` VARCHAR(50));
insert into `Cat 5e Cables`  values ( '27096', '27096', NULL, NULL, '1', 'Black', '8 x 6.8 x 3 inches', NULL, '2.3 pounds', NULL, 'gaming', NULL, '$19.99', '100 Feet');
insert into `Cat 5e Cables`  values ( 'N002-007-BK', NULL, 'Windows', 'Tripp Lite', NULL, NULL, '7 x 7 x 0.5 inches', 'Black', '2.4 ounces', '7 x 7 x 0.5 inches', NULL, 'Pc', '$4.60', NULL);
insert into `Cat 5e Cables`  values ( '19145', '19145', NULL, NULL, '1', 'Grey', '10.8 x 6 x 4.8 inches', NULL, '1 pounds', NULL, 'gaming', NULL, '$45.28', '200 Feet');
create table `SD & SDHC Cards` (`price` VARCHAR(50),`RAM` VARCHAR(50),`Hard Drive` VARCHAR(50));
insert into `SD & SDHC Cards`  values ( '$6.99', '4 GB', '4 GB');
create table `MP3 Players` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Power Source Type` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `MP3 Players`  values ( NULL, '1', 'Nextar', '6.5 x 2.5 x 8 inches', NULL, '7.2 ounces', 'NULL');
insert into `MP3 Players`  values ( NULL, '1', 'Panasonic', '8 x 7 x 3 inches', 'Corded-Electric, Battery', '7.2 ounces', '$99.98');
insert into `MP3 Players`  values ( NULL, '1', 'GPX', '6.4 x 1 x 6.1 inches', NULL, '4 ounces', 'NULL');
insert into `MP3 Players`  values ( NULL, NULL, 'Creative Labs', NULL, 'AC & Battery', NULL, 'NULL');
insert into `MP3 Players`  values ( 'VL-535A', '1', 'Visual Land', '3.1 x 0.6 x 1.2 inches', 'Battery', '2.6 ounces', 'NULL');
create table `CPU Cooling Fans` (`Item model number` VARCHAR(50),`Hardware Platform` VARCHAR(50),`Operating System` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Color` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`price` VARCHAR(50));
insert into `CPU Cooling Fans`  values ( 'FANDURONTB', 'Pc', 'Windows', 'StarTech', '3.9 x 2.5 x 5.8 inches', 'Black', '7.8 ounces', '3.94 x 2.52 x 5.75 inches', '$12.02');
create table `Backpacks` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50),`Item Weight` VARCHAR(50),`Screen Size` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `Backpacks`  values ( NULL, NULL, 'NULL', NULL, '17 inches', NULL);
insert into `Backpacks`  values ( '340140176', 'Samsonite', 'NULL', '2.4 pounds', NULL, '19.5 x 17 x 3.2 inches');
create table `Coaxial Speakers` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Warranty` VARCHAR(50));
insert into `Coaxial Speakers`  values ( '6 pounds', 'POWERPLUS652C', '17.5 x 7.7 x 3.5 inches', 'NULL', 'ONE YEAR');
insert into `Coaxial Speakers`  values ( '8.9 pounds', 'CJ-DA6923U', '5.9 x 18.9 x 11.6 inches', 'NULL', NULL);
insert into `Coaxial Speakers`  values ( '10.5 pounds', NULL, NULL, 'NULL', NULL);
insert into `Coaxial Speakers`  values ( '7.5 pounds', 'KS 52', '15.5 x 8.2 x 6.2 inches', 'NULL', NULL);
create table `Home Theater Systems` (`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Home Theater Systems`  values ( 'NULL', 'Mirage');
create table `USB Cables` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50),`Item Weight` VARCHAR(50),`Item Dimensions  L x W x H` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `USB Cables`  values ( NULL, 'Generic', 'NULL', NULL, NULL, NULL);
insert into `USB Cables`  values ( 'F3U001', 'Belkin', '$12.37', '0.8 ounces', '9 x 4.75 x 2 inches', '9 x 4.8 x 2 inches');
insert into `USB Cables`  values ( 'SCR-0755-31', 'Gomadic', '$17.67', '2.4 ounces', NULL, NULL);
create table `Motherboards` (`price` VARCHAR(50),`RAM` VARCHAR(50));
insert into `Motherboards`  values ( 'NULL', 'ddr');
create table `Boomboxes` (`price` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Boomboxes`  values ( 'NULL', '1', 'Emerson');
create table `Darkroom Supplies` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Darkroom Supplies`  values ( '17.6 pounds', 'VPLHS3', '6.6 x 12 x 12.6 inches', 'NULL', 'Sony');
create table `Satellite Radio` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Expansion` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Satellite Radio`  values ( 'AAI-NIS2', '1 YEAR', '8.5 x 4 x 1.8 inches', NULL, '1 pounds', 'NULL');
insert into `Satellite Radio`  values ( 'SR-04', NULL, '11.2 x 8.4 x 5.8 inches', NULL, '2 pounds', 'NULL');
insert into `Satellite Radio`  values ( NULL, NULL, NULL, 'Satellite Radio optional', NULL, 'NULL');
create table `Chargers & Cables` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Chargers & Cables`  values ( '0.3 ounces', 'USB', '6.6 x 5.2 x 0.7 inches', 'NULL', NULL);
insert into `Chargers & Cables`  values ( '2.4 ounces', 'EBC-0919-21', NULL, '$19.89', NULL);
insert into `Chargers & Cables`  values ( '2.4 ounces', 'RCC-1041-29', NULL, '$19.78', 'Gomadic');
create table `Wall Chargers` (`Item model number` VARCHAR(50),`price` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Wall Chargers`  values ( 'FG01267', '$82.95', '1', 'Niles');
create table `Antennas` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Weight` VARCHAR(50),`Brand` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`Cover Included` VARCHAR(50),`Model` VARCHAR(50),`price` VARCHAR(50));
insert into `Antennas`  values ( NULL, NULL, NULL, NULL, 'Metra', 'AW-TY205', '8.8 ounces', NULL, NULL, 'NULL');
insert into `Antennas`  values ( 'AXT48', 'ONE YEAR', '9 x 3.2 x 1.2 inches', '3.2 Ounces', NULL, NULL, '3.2 ounces', NULL, NULL, '$7.99');
insert into `Antennas`  values ( '5230', NULL, '168 x 2 x 2 inches', NULL, 'Shakespeare', '5230', '12 pounds', 'Shakespeare 5230 Galaxy VHF Marine Band Antenna, 14', '5230', '$288.83');
create table `MP3 Player Accessories` (`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`price` VARCHAR(50),`Power Source Type` VARCHAR(50),`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `MP3 Player Accessories`  values ( '1', NULL, 'NULL', NULL, NULL, NULL);
insert into `MP3 Player Accessories`  values ( '1', 'Beats', 'NULL', 'Corded-Electric, Battery', '1 pounds', '10 x 7 x 3 inches');
insert into `MP3 Player Accessories`  values ( '1', NULL, 'NULL', NULL, NULL, NULL);
create table `DVD Recorders` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Built In Decoders` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `DVD Recorders`  values ( 'Made in USA or Imported', 'DMR-EZ27K', 'Panasonic', '10 x 17 x 2 inches', 'Dolby Digital // DTS decoder', '6.2 pounds', '2 AA batteries required. (included)', NULL, 'Black', 'NULL');
insert into `DVD Recorders`  values ( NULL, 'DMR-E500HS', 'Panasonic', '10.9 x 16.9 x 3.1 inches', NULL, '13 pounds', '2 AA batteries required. (included)', 'Yes', NULL, 'NULL');
create table `TV Antennas` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`price` VARCHAR(50));
insert into `TV Antennas`  values ( 'HDTVLP', 'Terk', '5 x 4 x 30 inches', '3 pounds', NULL, 'NULL');
insert into `TV Antennas`  values ( NULL, 'Recoton', NULL, '1 pounds', 'Yes', 'NULL');
create table `Headrest Video` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Display Type` VARCHAR(50),`price` VARCHAR(50),`Weight` VARCHAR(50));
insert into `Headrest Video`  values ( '5.8 pounds', 'RBPL71HRGR', 'LCD', 'NULL', '5.8 Pounds');
create table `Vehicle GPS` (`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50),`Display Size` VARCHAR(50));
insert into `Vehicle GPS`  values ( '1.1 pounds', '8.2 x 6.3 x 2.8 inches', '$19.99', '5 inches');
create table `Car Stereo Receivers` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Chassis Size` VARCHAR(50),`Wireless Remote` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Car Stereo Receivers`  values ( NULL, NULL, NULL, 'No', '12.2 x 9 x 5 inches', '5.5 pounds', 'NULL');
insert into `Car Stereo Receivers`  values ( 'MEX1GP', '1 year warranty', NULL, 'No', NULL, '3.9 pounds', 'NULL');
insert into `Car Stereo Receivers`  values ( 'DFZ675MC', 'ONE YEAR', 'Double-DIN', NULL, '11.9 x 9.7 x 7.7 inches', '6.4 pounds', 'NULL');
create table `Radio Accessories` (`Item model number` VARCHAR(50),`Warranty` VARCHAR(50),`Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Radio Accessories`  values ( 'FD1420B', 'ONE YEAR', '5.76 Ounces', '16.5 x 8.5 x 1.5 inches', '5.8 ounces', '$13.97');
insert into `Radio Accessories`  values ( NULL, NULL, NULL, NULL, '4 ounces', '$15.96');
create table `Video Converters` (`Item model number` VARCHAR(50),`price` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50));
insert into `Video Converters`  values ( 'A105076', 'NULL', '1', 'X3D Technologies');
create table `GPS System Accessories` (`Item Weight` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50));
insert into `GPS System Accessories`  values ( '4.8 ounces', 'A47_25Qpl8', '5.3 x 4.2 x 1.2 inches', '$23.91');
create table `Professional Photo Albums` (`Item Weight` VARCHAR(50),`Product Dimensions` VARCHAR(50),`price` VARCHAR(50));
insert into `Professional Photo Albums`  values ( '1.4 pounds', '9.1 x 7.4 x 2.1 inches', 'NULL');
create table `DVD Players & Recorders` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `DVD Players & Recorders`  values ( 'Imported (Malaysia)', 'DVPCX985V', 'Sony', '23 x 23 x 13 inches', '19 pounds', 'Yes', 'Black', 'NULL');
insert into `DVD Players & Recorders`  values ( 'Imported (Taiwan)', 'DSR-1', 'Simotech', '10 x 9 x 9 inches', '9 pounds', NULL, 'White with blue top.', '$120.00');
insert into `DVD Players & Recorders`  values ( NULL, 'DVD-F65S', 'Panasonic', '15.7 x 16.9 x 2.4 inches', '7 pounds', 'Yes', 'Silver', 'NULL');
insert into `DVD Players & Recorders`  values ( NULL, NULL, 'Kenwood', NULL, NULL, NULL, NULL, 'NULL');
create table `Wiring Harnesses` (`Item model number` VARCHAR(50),`Weight` VARCHAR(50),`Brand` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50),`Product Dimensions` VARCHAR(50));
insert into `Wiring Harnesses`  values ( NULL, NULL, 'Carxtc', '2.1 ounces', '$9.99', NULL);
insert into `Wiring Harnesses`  values ( NULL, NULL, NULL, '2.1 ounces', '$9.99', NULL);
insert into `Wiring Harnesses`  values ( 'FDK9B', '2.24 Ounces', NULL, '0.5 ounces', '$6.95', '4 x 1 x 6 inches');
create table `DVD-VCR Combos` (`Item model number` VARCHAR(50),`Origin` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `DVD-VCR Combos`  values ( 'MVD4540', NULL, 'Memorex', '17 x 12 x 3.8 inches', '10 pounds', '2 AA batteries required.', 'Yes', NULL, 'NULL');
insert into `DVD-VCR Combos`  values ( 'DVP3150V/37', 'Made in USA', 'Philips', '9.2 x 17.1 x 3.7 inches', '7.8 pounds', NULL, NULL, NULL, 'NULL');
insert into `DVD-VCR Combos`  values ( 'ADV-3800', NULL, 'Apex', '19.6 x 17.1 x 6.8 inches', '16.2 pounds', NULL, 'Yes', NULL, 'NULL');
insert into `DVD-VCR Combos`  values ( 'NS-DRVCR', 'Made in USA or Imported', 'Insignia', '12.2 x 16.9 x 3.1 inches', NULL, NULL, NULL, 'Silver', 'NULL');
create table `Tablets` (`price` VARCHAR(50),`Screen Size` VARCHAR(50),`Processor` VARCHAR(50));
insert into `Tablets`  values ( 'NULL', '10 inches', 'Intel StrongARM');
create table `Laminating Supplies` (`Item model number` VARCHAR(50),`Number of Items` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Laminating Supplies`  values ( '013623', '1', 'Royal', '10 x 12 x 1 inches', '013623', '1.6 pounds', 'NULL');
create table `TV-DVD Combos` (`Item model number` VARCHAR(50),`Brand Name` VARCHAR(50),`Product Dimensions` VARCHAR(50),`Item Weight` VARCHAR(50),`Batteries` VARCHAR(50),`California residents` VARCHAR(50),`Discontinued by manufacturer` VARCHAR(50),`Color Name` VARCHAR(50),`price` VARCHAR(50));
insert into `TV-DVD Combos`  values ( 'LCT2701AD', 'Akai', '28 x 10 x 22 inches', '36.6 pounds', '2 AA batteries required. (included)', 'Click here for Proposition 65 warning', NULL, 'Black/Silver', 'NULL');
insert into `TV-DVD Combos`  values ( '43H71', 'Toshiba', '20.2 x 38 x 42.8 inches', '118 pounds', NULL, NULL, 'Yes', NULL, 'NULL');
insert into `TV-DVD Combos`  values ( 'MW24FP1', 'Toshiba', '20.5 x 20.2 x 25.8 inches', '80 pounds', NULL, NULL, 'Yes', NULL, 'NULL');
create table `Cables` (`Origin` VARCHAR(50),`Item model number` VARCHAR(50),`Product Dimensions` VARCHAR(50),`OEM Part Number` VARCHAR(50),`Brand` VARCHAR(50),`Manufacturer Part Number` VARCHAR(50),`Item Weight` VARCHAR(50),`price` VARCHAR(50));
insert into `Cables`  values ( 'China', '2431', '0.3 x 0.3 x 0.2 inches', '2431', 'Spectre Performance', '2431', '7.7 ounces', '$27.99');
